../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.025 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.050 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.075 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.100 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.125 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.150 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.175 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.200 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.250 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.300 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.350 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.400 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.450 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
../../build/noxim -config ../../config_examples/strawman/mesh_18x10_mod_dor.yaml -ir 0.500 poisson -sim 10000 -detailed -log_file_name ../results/strawman/8
