../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.025 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.050 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.075 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.100 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.125 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.150 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.175 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.200 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.225 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.250 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.275 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.300 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.325 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.350 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.375 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.400 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.425 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.450 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.475 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.500 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.600 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.700 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.800 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.900 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
../build/noxim -config ../config_examples/latencies/mesh_10x10_dor.yaml -pir 1.000 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/latencies/checker_dor
