../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.05 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.10 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.15 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.20 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.25 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.30 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.35 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.40 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.50 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.60 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.70 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.80 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 0.90 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
../build/noxim -config ../config_examples/perfect_routing/mesh_18x10_xy.yaml -pir 1.00 poisson -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/perfect_routing/xy
