# DOR all
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_05.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_10.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_15.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_20.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_25.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_30.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_35.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_40.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_50.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_60.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_70.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_80.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_0_90.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_base_1_00.csv

# DOR no angle
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_05.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_10.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_15.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_20.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_25.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_30.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_35.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_40.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_50.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_60.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_70.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_80.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_0_90.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_base_1_00.csv

# DOR 8MC
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_05.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_10.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_15.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_20.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_25.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_30.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_35.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_40.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_50.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_60.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_70.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_80.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_0_90.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_base_1_00.csv

# DOR 4MC
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_05.csv > ./results/14x14_p4_rd_4mc_base_0_05.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_10.csv > ./results/14x14_p4_rd_4mc_base_0_10.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_15.csv > ./results/14x14_p4_rd_4mc_base_0_15.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_20.csv > ./results/14x14_p4_rd_4mc_base_0_20.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_25.csv > ./results/14x14_p4_rd_4mc_base_0_25.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_30.csv > ./results/14x14_p4_rd_4mc_base_0_30.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_35.csv > ./results/14x14_p4_rd_4mc_base_0_35.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_40.csv > ./results/14x14_p4_rd_4mc_base_0_40.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_50.csv > ./results/14x14_p4_rd_4mc_base_0_50.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_60.csv > ./results/14x14_p4_rd_4mc_base_0_60.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_70.csv > ./results/14x14_p4_rd_4mc_base_0_70.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_80.csv > ./results/14x14_p4_rd_4mc_base_0_80.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_0_90.csv > ./results/14x14_p4_rd_4mc_base_0_90.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_base_1_00.csv > ./results/14x14_p4_rd_4mc_base_1_00.log


# Modified DOR 8MC
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_05.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_10.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_15.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_20.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_25.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_30.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_35.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_40.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_50.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_60.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_70.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_80.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_0_90.csv > ./results/14x14_p4_rd_8mc_mdor_0_90.log
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_8mc_mdor_1_00.csv > ./results/14x14_p4_rd_8mc_mdor_1_00.log

# Modified DOR 4MC
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_05.csv > ./results/14x14_p4_rd_4mc_mdor_0_05.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_10.csv > ./results/14x14_p4_rd_4mc_mdor_0_10.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_15.csv > ./results/14x14_p4_rd_4mc_mdor_0_15.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_20.csv > ./results/14x14_p4_rd_4mc_mdor_0_20.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_25.csv > ./results/14x14_p4_rd_4mc_mdor_0_25.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_30.csv > ./results/14x14_p4_rd_4mc_mdor_0_30.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_35.csv > ./results/14x14_p4_rd_4mc_mdor_0_35.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_40.csv > ./results/14x14_p4_rd_4mc_mdor_0_40.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_50.csv > ./results/14x14_p4_rd_4mc_mdor_0_50.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_60.csv > ./results/14x14_p4_rd_4mc_mdor_0_60.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_70.csv > ./results/14x14_p4_rd_4mc_mdor_0_70.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_80.csv > ./results/14x14_p4_rd_4mc_mdor_0_80.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_0_90.csv > ./results/14x14_p4_rd_4mc_mdor_0_90.log
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 5 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 2000 -detailed -log_file_name ./results/14x14_p4_rd_4mc_mdor_1_00.csv > ./results/14x14_p4_rd_4mc_mdor_1_00.log

# Interleaving all
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_05.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_10.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_15.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_20.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_25.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_30.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_35.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_40.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_50.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_60.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_70.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_80.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_0_90.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_il_1_00.csv

# Interleaving no angle
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_05.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_10.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_15.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_20.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_25.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_30.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_35.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_40.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_50.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_60.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_70.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_80.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_0_90.csv
# ../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -req_ack_mode 1 -sim 10000 -detailed -log_file_name ./results/14x14_p4_rd_no_angle_il_1_00.csv
