# Modified DOR 8 MC 1 packet size
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -sim 10000 -detailed -log_file_name ./results/burst

# Modified DOR 8 MC 2 packet size
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 2 -sim 10000 -detailed -log_file_name ./results/burst

# Modified DOR 8 MC 4 packet size
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 4 -sim 10000 -detailed -log_file_name ./results/burst

# Modified DOR 8 MC 8 packet size
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 8 -sim 10000 -detailed -log_file_name ./results/burst

# Modified DOR 8 MC 16 packet size
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 16 -sim 10000 -detailed -log_file_name ./results/burst
