# Mesh 10x10 + DOR + 1p
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.025 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.050 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.075 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.100 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.125 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.150 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.175 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.200 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.250 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.300 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.350 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.400 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.450 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.500 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.000 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper

# Mesh 10x10 + DOR + 4p
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.025 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.050 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.075 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.100 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.125 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.150 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.175 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.200 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.250 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.300 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.350 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.400 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.450 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.500 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.000 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper

# Mesh 10x10 + DOR + 1p + interleaving
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.025 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.050 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.075 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.100 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.125 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.150 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.175 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.200 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.250 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.300 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.350 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.400 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.450 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.500 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.000 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper

# Mesh 10x10 + MOD_DOR + 1p
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.025 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.050 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.075 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.100 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.125 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.150 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.175 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.200 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.250 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.300 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.350 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.400 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.450 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.500 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.000 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper

# Mesh 10x10 + DOR + 4p + interleaving
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.025 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.050 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.075 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.100 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.125 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.150 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.175 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.200 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.250 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.300 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.350 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.400 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.450 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.500 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.000 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper

# Mesh 10x10 + MOD_DOR + 4p
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.025 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.050 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.075 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.100 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.125 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.150 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.175 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.200 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.250 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.300 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.350 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.400 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.450 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.500 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.000 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper

# Mesh 10x10 + MOD_DOR + 1p + interleaving
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.025 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.050 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.075 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.100 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.125 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.150 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.175 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.200 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.250 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.300 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.350 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.400 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.450 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.500 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.000 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper

# Mesh 10x10 + MOD_DOR + 4p + interleaving
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.025 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.050 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.075 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.100 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.125 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.150 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.175 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.200 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.250 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.300 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.350 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.400 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.450 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.500 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.000 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation_paper
