# DOR 4 MC 1 packet size
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
../build/noxim -config ../config_examples/mesh_18x10_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 3 -req_ack_mode 1 -both_phys_req_mode 1 -size 1 1 -traffic_burst_size 16 -sim 10000 -detailed -log_file_name ./results/burst
