#########################################################################################
# Base DOR
#########################################################################################
# Base DOR all nodes
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_dor_1_00.csv

# Base DOR switch angles
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_dor_1_00.csv

# Base DOR 8 MC left
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_dor_1_00.csv

# Base DOR 4 MC left
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_dor_1_00.csv

#########################################################################################
# Base DOR end
#########################################################################################

#########################################################################################
# Interleaving
#########################################################################################
# Interleaving all nodes
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_dor_1_00.csv

# Interleaving switch angles
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_dor_1_00.csv

#########################################################################################
# Interleaving end
#########################################################################################

#########################################################################################
# Modified DOR
#########################################################################################
# Modified DOR all nodes
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_mdor_1_00.csv

# Modified DOR switch angles
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_mdor_1_00.csv

# Modified DOR 8 MC left
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 3 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_8mc_mdor_1_00.csv

# Modified DOR 4 MC left
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 5 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_4mc_mdor_1_00.csv

#########################################################################################
# Modified DOR end
#########################################################################################

#########################################################################################
# Modified DOR + Interleaving
#########################################################################################

# Interleaving + Modified DOR all nodes
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_all_il_mdor_1_00.csv

# Interleaving + Modified DOR switch angles
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_05.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_10.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_15.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_20.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_25.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_30.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_35.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_40.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_50.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_60.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_70.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_80.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_0_90.csv
../bin/noxim -config ../config_examples/mesh_14x14_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 1 -switch_horizontal_masters 0 -sim 10000 -detailed -log_file_name ./results/14x14_p4_angles_il_mdor_1_00.csv

#########################################################################################
# Modified DOR + Interleaving end
#########################################################################################
