# Mesh 10x10 + DOR + 1p
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation

# Mesh 10x10 + DOR + 4p
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 0 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation

# Mesh 10x10 + DOR + 1p + interleaving
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.05 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.10 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.15 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.20 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.25 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.30 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.35 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.40 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.50 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.60 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.70 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.80 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.90 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.00 poisson -routing DOR -interliving_reps 1 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation

# Mesh 10x10 + MOD_DOR + 1p
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 0 -mem_ports 1 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation

# Mesh 10x10 + MOD_DOR + 4p
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.05 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.10 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.15 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.20 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.25 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.30 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.35 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.40 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.50 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.60 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.70 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.80 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 0.90 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
# ../bin/noxim -config ../config_examples/mesh_10x10_interliving.yaml -pir 1.00 poisson -routing MOD_DOR -interliving_reps 1 -mem_ports 4 -switch_angle_masters 0 -switch_horizontal_masters 0 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ./results/collision_mitigation
