../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.025 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.050 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.075 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.100 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.125 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.150 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.175 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.200 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.225 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.250 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.275 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.300 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.325 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.350 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.375 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.400 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.425 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.450 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.475 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.500 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.600 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.700 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.800 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 0.900 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
../../build/noxim -config ../../config_examples/latencies/mesh_10x10_dor.yaml -pir 1.000 poisson -sim 10000 -detailed -log_file_name ../results/latencies/checker_dor
