../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.05 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.10 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.15 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.20 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.25 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.30 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.35 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.40 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.50 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.60 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.70 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.80 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 0.90 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
../../build/noxim -config ../../config_examples/vertical_connection/mesh_18x10_dor.yaml -ir 1.00 poisson -sim 10000 -detailed -log_file_name ../results/vertical_connection/base
