# Mesh 10x10 + MOD_DOR + 1p + interleaving
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.05 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.10 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.15 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.20 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.25 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.30 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.35 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.40 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.50 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.60 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.70 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.80 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 0.90 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
../../build/noxim -config ../../config_examples/phd_2/mesh_10x10_mod_dor.yaml -pir 1.00 poisson -interliving_reps 1 -req_ack_mode 1 -both_phys_req_mode 1 -sim 10000 -detailed -log_file_name ../results/phd_2/mod_dor_1p_il
