../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.05 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.10 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.15 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.20 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.25 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.30 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.35 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.40 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.50 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.60 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.70 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.80 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 0.90 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
../../build/noxim -config ../../config_examples/phd_4/mesh_10x6_horizontal_yx.yaml -pir 1.00 poisson -sim 10000 -detailed -log_file_name ../results/phd_4/7_1
